name: Publish Snapshot

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

jobs:
  snapshot:
    name: Publish snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD

      - name: Deploy snapshot
        run: ./mvnw -B --no-transfer-progress deploy -Psb4
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
